const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Game_Event1_Act2,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.Game_Event28_Act2,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Cnds.OnAnimFinished
	];
};
self.C3_JsPropNameTable = [
	{symbols: 0},
	{Touch: 0},
	{Text: 0},
	{baseS: 0},
	{Keyboard: 0},
	{"9patch": 0},
	{betAmountTxt: 0},
	{win: 0},
	{infoTxt: 0},
	{totalMultiplierTxt: 0},
	{id: 0},
	{freespinInfo: 0},
	{Sine: 0},
	{title: 0},
	{Tween: 0},
	{bw_glow_back_: 0},
	{totalWinTxt: 0},
	{tumble: 0},
	{multiplierSymbol: 0},
	{wukong: 0},
	{Audio: 0},
	{gui_cloud2: 0},
	{gui_cloud: 0},
	{Family1: 0},
	{Family2: 0},
	{music: 0},
	{sound: 0},
	{symbol: 0},
	{multiplier: 0},
	{totalwin: 0},
	{awardedSpins: 0},
	{remainingSpins: 0},
	{scatterCount: 0},
	{finalAccumulatedMultiplier: 0},
	{totalSessionWin: 0},
	{remaining: 0},
	{currentTotalMultiplier: 0},
	{totalWin: 0},
	{info: 0},
	{type: 0}
];

self.InstanceType = {
	symbols: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	baseS: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	_9patch: class extends self.I9PatchInstance {},
	betAmountTxt: class extends self.ITextInstance {},
	win: class extends self.ISpriteInstance {},
	infoTxt: class extends self.ITextInstance {},
	totalMultiplierTxt: class extends self.ITextInstance {},
	freespinInfo: class extends self.I9PatchInstance {},
	title: class extends self.ISpriteInstance {},
	bw_glow_back_: class extends self.ISpriteInstance {},
	totalWinTxt: class extends self.ITextInstance {},
	tumble: class extends self.ISpriteInstance {},
	multiplierSymbol: class extends self.ISpriteFontInstance {},
	wukong: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	gui_cloud2: class extends self.ISpriteInstance {},
	gui_cloud: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	Family2: class extends self.ITextInstance {}
}